name: Build app
run-name: Build app
on: [ push ]

jobs:
  Build:
    runs-on: ubuntu-24.04
    container:
      image: "node:18.15.0-slim"
    steps:
      - uses: https://github.com/actions/checkout@v4
      - run: npm ci
      - run: npm run build
      - name: Publish page
        run: ftp -u ftp://${{ secrets.FTP_USER }}:${{ secrets.FTP_PASS }}@${{ vars.FTP_HOST }}/ dist/**/*