name: Build app
run-name: Build app
on: [ push ]

jobs:
  Build:
    runs-on: ubuntu-24.04
    container:
      image: "node:18.15.0-slim"
    steps:
      - uses: https://github.com/actions/checkout@v4
      - run: npm ci
      - run: npm run build
      - name: Create .htaccess file
        run: cd dist && touch .htaccess && echo ${{ vars.HTACCESS_CONTENT }} >> .htaccess
      - name: Publish page
        uses: https://github.com/SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ vars.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          dangerous-clean-slate: true
          local-dir: ./dist/