name: Build app
run-name: Build app
on: [ push ]

jobs:
  Build:
    runs-on: ubuntu-24.04
    container:
      image: "node:18.15.0-slim"
    steps:
      - uses: https://github.com/actions/checkout@v4
      - run: npm ci
      - run: npm run build
      - name: Upload artifact
        uses: https://github.com/actions/upload-artifact@v4
        with:
          name: cv-dist
          path: dist/*